### PR TITLE
#305 with versions CPP

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by treeowl** [comment]
Oh, does this address the problems with the earlier PR?

**Comment by phadej** [comment]
as far as I can tell, yes. let's see if CI agrees.

**Review by sjakobi — APPROVED** [review]

**Comment by treeowl** [comment]
Thanks!

**Comment by phadej** [comment]
It would be great if you could make a release with this patch

**Comment by sjakobi** [comment]
> It would be great if you could make a release with this patch

Done! http://hackage.haskell.org/package/unordered-containers-0.2.14.0

**Comment by phadej** [comment]
@sjakobi thanks!

**Pull request merged**
