### PR TITLE
Remove custom unsafeShift{L,R} definitions

### PR DESCRIPTION
**Pull request by sjakobi**
These have been available from base since v4.5.

### CODE REVIEW

**Comment by treeowl** [comment]
IIRC the question in containers was whether these had the same inlining
behavior.

**Comment by sjakobi** [comment]
> IIRC the question in containers was whether these had the same inlining behavior.

Can you give more detail, or just a link to that discussion?

I just had a look at the changes in the generated Core for `Data.HashMap.Base` with GHC 8.10.1 and the only differences I could find were in some source locations due to the removal of the import statement.

Is there a better way to inspect the inlining behaviour here?

**Comment by treeowl** [comment]
Well, if GHC generates the same unfoldings with the same inlining guidance,
I think we should be good. As I recall, some of the bitty functions in base
don't/didn't have explicit INLINE pragmas, which can affect whether they
get inlined into unfoldings.

**Comment by sjakobi** [comment]
I just compared the Core generated with 7.8.4 (the oldest GHC version we support) and there are quite a lot of differences.

I'll have to take a closer look. Maybe we can figure out the earliest GHC version that does the desired inlining and move the custom  `unsafeShift*` definitions behind some CPP…

**Comment by treeowl** [comment]
No. CPP is for compatibility, not extreme performance. I don't care if there are perf regressions on 7.8.

**Comment by sjakobi** [comment]
In order to get more insight into the inlining behaviour, I've extracted this bit of code:

```haskell
-- shift.hs
module M (mask) where

import Data.Bits
import Data.Word

bitsPerSubkey :: Int
bitsPerSubkey = 4

subkeyMask :: Word
subkeyMask = 1 `unsafeShiftL` bitsPerSubkey - 1

mask :: Word -> Int -> Int
mask w s = 1 `unsafeShiftL` index w s
{-# INLINE mask #-}

index :: Word -> Int -> Int
index w s = fromIntegral $ unsafeShiftR w s .&. subkeyMask
{-# INLINE index #-}
```

I've compared the Core produced for this module with `ghc -O` with GHC 7.8.4 and up. The only significant change seems to happen from 8.0.2 to 8.2.2 in the unfolding `Tmpl`:

```diff
 mask [InlPrag=INLINE (sat-args=2)] :: Word -> Int -> Int
 [GblId,
  Arity=2,
  Caf=NoCafRefs,
- Str=DmdType <S(S),1*U(U)><S(S),1*U(U)>m,
+ Str=<S(S),1*U(U)><S(S),1*U(U)>m,
  Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
          WorkFree=True, Expandable=True,
          Guidance=ALWAYS_IF(arity=2,unsat_ok=False,boring_ok=False)
-         Tmpl= \ (w [Occ=Once] :: Word) (s [Occ=Once] :: Int) ->
-                 Data.Bits.$fBitsInt_$cunsafeShiftL
-                   (GHC.Types.I# 1#)
-                   ($ @ 'GHC.Types.PtrRepLifted
-                      @ Word
-                      @ Int
-                      (\ (ds [Occ=Once!] :: Word) ->
-                         case ds of _ [Occ=Dead] { GHC.Types.W# x# [Occ=Once] ->
-                         GHC.Types.I# (GHC.Prim.word2Int# x#)
-                         })
-                      (Data.Bits.$fBitsWord_$c.&.
-                         (Data.Bits.$fBitsWord_$cunsafeShiftR w s) subkeyMask))}]
-mask =
-  \ (w :: Word) (s :: Int) ->
-    case w of _ [Occ=Dead] { GHC.Types.W# x# ->
-    case s of _ [Occ=Dead] { GHC.Types.I# i# ->
-    GHC.Types.I#
-      (GHC.Prim.uncheckedIShiftL#
-         1#
-         (GHC.Prim.word2Int#
-            (GHC.Prim.and# (GHC.Prim.uncheckedShiftRL# x# i#) 15##)))
-    }
-    }
+         Tmpl= \ (w [Occ=Once!] :: Word) (s [Occ=Once!] :: Int) ->
+                 case w of { GHC.Types.W# x# [Occ=Once] ->
+                 case s of { GHC.Types.I# i# [Occ=Once] ->
+                 GHC.Types.I#
+                   (GHC.Prim.uncheckedIShiftL#
+                      1#
+                      (GHC.Prim.word2Int#
+                         (GHC.Prim.and# (GHC.Prim.uncheckedShiftRL# x# i#) 15##)))
+                 }
+                 }}]
+mask
+  = \ (w :: Word) (s :: Int) ->
+      case w of { GHC.Types.W# x# ->
+      case s of { GHC.Types.I# i# ->
+      GHC.Types.I#
+        (GHC.Prim.uncheckedIShiftL#
+           1#
+           (GHC.Prim.word2Int#
+              (GHC.Prim.and# (GHC.Prim.uncheckedShiftRL# x# i#) 15##)))
+      }
+      }
```

With 8.0.2 the unfolding still references the `unsafeShift[L,R]` methods – with 8.2.2, the unfolding uses the primops directly.

Based on this insight, I'd suspect that this PR would cause a performance deterioration with GHC < 8.2.

**Comment by sjakobi** [comment]
> Based on this insight, I'd suspect that this PR would cause a performance deterioration with GHC < 8.2.

Indeed benchmarks with GHC 8.0.2 seem to indicate a small hit, mostly on the order of 1–6%.

I think the simplification might still be worth it.

**Comment by sjakobi** [comment]
I was somewhat on the fence about this patch, since it kind of prioritizes maintainability over performance, but I guess I don't care enough about users of GHC 7.8, 7.10 and 8.0.

**Pull request merged**
