### PR TITLE
Prepare release 0.2.12.0

### PR DESCRIPTION
**Pull request by sjakobi**
Hackage candidate: https://hackage.haskell.org/package/unordered-containers-0.2.12.0/candidate

### CODE REVIEW

**Comment by sjakobi** [comment]
@treeowl, @emilypi Would you like to review?

**Comment by treeowl** [comment]
Not really. I'm giving a talk at the Haskell Love conference (Free! Online! Please come!) on Saturday and I'm totally tied up with prep until then. If everything looks obviously fine, you can go ahead and release.

**Comment by treeowl** [comment]
If you have any doubts, I should be able to have a look later in the weekend.

**Comment by sjakobi** [comment]
> I'm giving a talk at the Haskell Love conference (Free! Online! Please come!) on Saturday and I'm totally tied up with prep until then.

Oooh! https://haskell.love/agenda-day-2/

That's 18:15 for me in CEST. I'll try to watch your talk live. :)

**Comment by treeowl** [comment]
I look forward to having you there!

**Comment by sjakobi** [comment]
In case anyone wants to help spread the hype, please be my guest! ;)

* https://www.reddit.com/r/haskell/comments/i3uois/unorderedcontainers_v02120/
* https://twitter.com/SimonJakobi/status/1290798990502645763

**Pull request merged**
