### PR TITLE
Allow template-haskell-2.21 (GHC-9.8)

### PR DESCRIPTION
**Pull request by phadej**
Update CI: add GHC-9.6 and GHC-9.8 jobs, bump minor version of recent GHCs

Looks like revision 2 https://hackage.haskell.org/package/unordered-containers-0.2.19.1/revisions/ was never merged in. I cannot find an issue or pull request, @andreasabel?

### CODE REVIEW

**Comment by treeowl** [comment]
Thanks!

**Comment by phadej** [comment]
@treeowl thanks. Could you make a revision (or a release including #debug e.g.)

**Comment by andreasabel** [comment]
@treeowl @phadej  Is there any reason to delay the revision?  This package has tons of customers, and any delay multiplies accordingly.  So, I would make the revision _now_.

**Comment by phadej** [comment]
@andreasabel I'm not a maintainer of `unordered-containers`. They are @treeowl and @sjakobi

**Comment by andreasabel** [comment]
Ok, I did revision 3: https://hackage.haskell.org/package/unordered-containers-0.2.19.1/revisions/ relative to `cabal get unordered-containers`.  The `master` has some additional commits, so cannot serve as a revision base atm.
I suppose the maintainers want to make a release soon, but having the revision out sooner rather than later helps the Haskell ecosystem to move forward.

**Pull request merged**
