### PR TITLE
u-c.cabal: Update maintainers

### PR DESCRIPTION
**Pull request by sjakobi**
This change reflects who has been doing active maintenance work in the past 2 years.

### CODE REVIEW

**Comment by sjakobi** [comment]
CC @emilypi: I know you intended to help maintain `u-c`, but since you haven't been very active in this project in the past 2 years, I didn't add you to the `maintainers` field.

**Comment by tibbe** [comment]
LGTM

**Review by tibbe — APPROVED** [review]

**Review by treeowl — APPROVED** [review]
Yep, you've definitely been leading maintenance here recently.

**Comment by treeowl** [comment]
I just added you as an owner of the GitHub organization.

**Comment by emilypi** [comment]
> CC @emilypi: I know you intended to help maintain `u-c`, but since you haven't been very active in this project in the past 2 years, I didn't add you to the `maintainers` field.

💯 i'm on board with that. I'm just an additional hand if needed, as opposed to active.

**Pull request merged**
