### PR TITLE
Support hashable-1.4

### PR DESCRIPTION
**Pull request by sjakobi**
https://hackage.haskell.org/package/hashable-1.4.0.0/changelog

### CODE REVIEW

**Comment by sjakobi** [comment]
I was wondering whether we should update constraints like `(Eq k, Hashable k)`. @phadej has convinced me not to do this for now in https://github.com/haskell-unordered-containers/hashable/issues/232#issuecomment-956200669. Instead, we can consider requiring `hashable >= 1.4` in a few months and enabling `-Wredundant-constraints` then.

**Comment by sjakobi** [comment]
Ping @treeowl. I'd like to make a release including this patch soon.

**Comment by phadej** [comment]
I checked that CI indeed picks up `hashable-1.4.0.0` as a dependency. Ping @treeowl .

In the meantime, @sjakobi do you mind adding 9.2.1 job to CI?

**Comment by treeowl** [comment]
Sounds like a plan.

**Review by treeowl — APPROVED** [review]

**Comment by sjakobi** [comment]
@phadej I've checked locally that this branch builds with GHC 9.2.1.

**Pull request merged**
