### PR TITLE
two: Avoid branch in computation of idx2

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
I haven't been able to find any changes in the benchmarks so far. The generated code looks better though.

**Comment by sjakobi** [comment]
> I'm a bit surprised GHC doesn't undo this optimization.

Yeah, GHC is pretty eager to generate a branch here. E.g. `idx2 = fromEnum (... < ...)` would still generate the branch.

**Comment by treeowl** [comment]
We have

```haskell
index :: Hash -> Shift -> Int
index w s = fromIntegral $ unsafeShiftR w s .&. subkeyMask
```

So I think another option would be to shift the `subKeyMask` left and use the result for both hashes. I dunno if that would be better, worse, or exactly the same.

**Comment by sjakobi** [comment]
Yes, there are more low-level tweaks that can be applied here. https://github.com/haskell-unordered-containers/unordered-containers/issues/468#issuecomment-1129040465 is related.

**Pull request merged**
